### ISSUE TITLE
CLI Feature Request: Read plain-text passwords from stdin.

### ISSUE THREAD

**Issue by tveastman** [lionheart/pwnedpasswords#1]
Great handy little tool! Thanks!

Rather than providing passwords on the command line (where experiments then end up stored in your shell history), it'd be convenient to read passwords from `sys.stdin`.

```
$ pwnedpasswords --stdin
bob
37883
password
3303003
[... etc ...]
```

**Comment by dlo** [comment]
Great idea! Thanks for the suggestion @tveastman 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
